[package]
name = "v11"
version = "0.2.0"
authors = ["neptunepink <purpleposeidon@gmail.com>"]

[dependencies]
rustc-serialize = "*"
itertools = "0.4.16"
joinkit = "0.2.0"
bit-vec = "0.4.3"
num-traits = "*"
lazy_static = "*"

# mopa = "0.2.*"
# "my own personal Any", allows downcasting or something.

# OwningRef: https://kimundi.github.io/owning-ref-rs/owning_ref/struct.OwningRef.html


