[package]
name = "v11"
version = "0.0.4"
authors = ["neptunepink <purpleposeidon@gmail.com>"]

[lib]
crate-type = ["rlib", "dylib"]

[dev-dependencies]
rand = "*"

[dependencies]
v11_macros = { path = "./macros" }
procedural-masquerade = "0.1.2"
rustc-serialize = "*"
itertools = "0.4.16"
# bit-vec = "0.4.3"
bit-vec-mut = { git = "https://github.com/purpleposeidon/bit-vec" }
num-traits = "*"
lazy_static = "*"

mopa = "0.2.*"
# "my own personal Any", allows downcasting or something.

# OwningRef: https://kimundi.github.io/owning-ref-rs/owning_ref/struct.OwningRef.html

# parking-lot is kind of awesome

[features]
doc = []
