[package]
name = "v11"
version = "0.0.2"
authors = ["neptunepink <purpleposeidon@gmail.com>"]

[workspace]
members = ["./v11_test"]


[dependencies]
v11_macros = { path = "./v11_macros" }
procedural-masquerade = "0.1.2"
rustc-serialize = "*"
itertools = "0.4.16"
joinkit = "0.2.0"
# bit-vec = "0.4.3"
bit-vec = { git = "https://github.com/purpleposeidon/bit-vec" }
num-traits = "*"
lazy_static = "*"

# mopa = "0.2.*"
# "my own personal Any", allows downcasting or something.

# OwningRef: https://kimundi.github.io/owning-ref-rs/owning_ref/struct.OwningRef.html


