[package]
name = "v11_test"
version = "0.1.0"
authors = ["neptunepink <purpleposeidon@gmail.com>"]

[dependencies]
v11 = { path = "../" }
v11_macros = { path = "../v11_macros" }
rustc-serialize = "*"

[lib]
path = "lib.rs"

