[package]
name = "v11_test"
version = "0.0.0"
authors = ["neptunepink <purpleposeidon@gmail.com>"]

[dependencies]
v11 = { path = "../" }
v11_macros = { path = "../v11_macros" }

[lib]
path = "lib.rs"

